language: cpp
matrix:
  include:
  - os: linux
    compiler: clang
    addons:
      apt:
        sources:
        # Clang 3.8
        - llvm-toolchain-precise-3.7
        # Newer CMake
        - george-edison55-precise-backports
        # Newer GCC
        - ubuntu-toolchain-r-test
        packages:
        - cmake
        - cmake-data
        - liblapack-dev
        - clang-3.7
        - libhdf5-serial-dev
        - libgsl0-dev
        - libgsl0ldbl
    env: OUR_CXX='clang++-3.7' OUR_CC='clang-3.7' BUILD_TYPE='release'
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - cmake
        - cmake-data
        - libhdf5-serial-dev
        - liblapack-dev
        - g++-5
        - libgsl0-dev
        - libgsl0ldbl
    env: OUR_CXX='g++-5' OUR_CC='gcc-5' BUILD_TYPE='release'
env:
    global:
    # should be limited to 4 on travis
    - OMP_NUM_THREADS=4
    # make cmake verbose
    - VERBOSE=1
install:
    - mkdir build
    - cd build
    - cmake -DCMAKE_C_COMPILER=$OUR_CC -DCMAKE_CXX_COMPILER=$OUR_CXX -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
    - make
script:
    # we put a timeout of 30 minues
    - travis_wait 30 make test
